
name: Build

on: [push, pull_request]

jobs:
  run-tests:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12]

    steps:
      - uses: actions/checkout@v4

      - name: Setup python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run tests
        run: |
          python -m pip install --upgrade pip
          pip install -e '.[dev]'
          CODECOV_TOKEN=${{ secrets.CODECOV_TOKEN }} tox

  pack-and-publish:
    name: Pack and publish
    runs-on: ubuntu-latest
    needs: run-tests

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Build wheel
        run: |
          make build

      - name: Publish package testpypi
        run: |
          make publish FLIT_INDEX_URL=https://test.pypi.org/legacy FLIT_PASSWORD=${{ secrets.TEST_PYPI_TOKEN }}

      - name: Publish package pypi
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        run: |
          make publish FLIT_INDEX_URL=https://upload.pypi.org/legacy FLIT_PASSWORD=${{ secrets.PYPI_TOKEN }}
