
name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheel on ubuntu
    runs-on: ubuntu

    steps:
      - uses: actions/checkout@v2

      # Used to host cibuildwheel
      - uses: actions/setup-python@v2

      - name: Build wheel
        run: pip wheel -w wheelhouse .
        # to supply options, put them in 'env', like:
        # env:
        #   CIBW_SOME_OPTION: value

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl

