
name: Build

on: [push, pull_request]

jobs:
  build:
    name: Build wheel on ubuntu
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9]

    steps:
      - uses: actions/checkout@v2
        
      - name: Setup python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run tests
        run: |
          python -m pip install --upgrade pip
          pip install wheel tox tox-gh-actions
          tox

      - name: Upload codecov
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)        
          
      - name: Build wheel
        run: pip wheel -w wheelhouse .
        # to supply options, put them in 'env', like:
        # env:
        #   CIBW_SOME_OPTION: value

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl

